name: ConMeter
channels:
  - pytorch
  - nvidia
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - absl-py=1.3.0=py37h06a4308_0
  - aiohttp=3.8.3=py37h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - async-timeout=4.0.2=py37h06a4308_0
  - asynctest=0.13.0=py_0
  - attrs=22.1.0=py37h06a4308_0
  - blas=1.0=mkl
  - blinker=1.4=py37h06a4308_0
  - bottleneck=1.3.5=py37h7deecbd_0
  - brotlipy=0.7.0=py37h27cfd23_1003
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.2.25=h06a4308_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - cairo=1.16.0=hb05425b_5
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.15.1=py37h74dc2b5_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py37h06a4308_0
  - cryptography=39.0.1=py37h9ce1e76_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cudatoolkit=11.8.0=h6a678d5_0
  - expat=2.6.4=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - fontconfig=2.14.1=h4c34cd2_2
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.3.3=py37h5eee18b_0
  - giflib=5.2.2=h5eee18b_0
  - glib=2.69.1=h4ff587b_1
  - gmp=6.3.0=h6a678d5_0
  - gnutls=3.6.15=he1e5248_0
  - google-auth=2.6.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.1=py_2
  - grpcio=1.42.0=py37hce63b2e_0
  - icu=58.2=he6710b0_3
  - idna=3.4=py37h06a4308_0
  - importlib-metadata=4.11.3=py37h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h5eee18b_3
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libboost=1.73.0=h28710b8_12
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libnpp=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=3.20.3=he621ea3_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=hffd6297_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.10.4=hcbfbd50_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown=3.4.1=py37h06a4308_0
  - markupsafe=2.1.1=py37h7f8727e_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - multidict=6.0.2=py37h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - numexpr=2.8.4=py37he184ba9_0
  - numpy=1.21.5=py37h6c91a56_3
  - numpy-base=1.21.5=py37ha15fc14_3
  - oauthlib=3.2.1=py37h06a4308_0
  - openbabel=3.1.1=py37h6aa62a1_2
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1w=h7f8727e_0
  - packaging=22.0=py37h06a4308_0
  - pcre=8.45=h295c915_0
  - pillow=9.4.0=py37h6a678d5_0
  - pip=22.3.1=py37h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - protobuf=3.20.3=py37h6a678d5_0
  - py-boost=1.73.0=py37h51133e4_12
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyjwt=2.4.0=py37h06a4308_0
  - pyopenssl=23.0.0=py37h06a4308_0
  - pysocks=1.7.1=py37_1
  - python=3.7.13=haa1d7c7_1
  - python_abi=3.7=2_cp37m
  - pytorch=1.13.1=py3.7_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py37h06a4308_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - setuptools=65.6.3=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - tensorboard=2.6.0=py_1
  - tensorboard-data-server=0.6.1=py37h52d8a92_0
  - tensorboard-plugin-wit=1.8.1=py37h06a4308_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=0.13.1=py37_cu117
  - torchvision=0.14.1=py37_cu117
  - typing-extensions=4.4.0=py37h06a4308_0
  - typing_extensions=4.4.0=py37h06a4308_0
  - urllib3=1.26.14=py37h06a4308_0
  - werkzeug=2.2.2=py37h06a4308_0
  - wheel=0.38.4=py37h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - yarl=1.8.1=py37h5eee18b_0
  - zipp=3.11.0=py37h06a4308_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
    - chembl-structure-pipeline==1.2.2
    - dill==0.3.7
    - docopt==0.6.2
    - et-xmlfile==1.1.0
    - joblib==1.3.2
    - openpyxl==3.1.3
    - pandas==1.3.5
    - pickle5==0.0.12
    - pipreqs==0.4.13
    - python-dateutil==2.9.0.post0
    - pytz==2025.1
    - rdkit==2023.3.2
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - tensorboardx==2.2
    - threadpoolctl==3.1.0
    - tqdm==4.67.1
    - yarg==0.1.10

